# Generated by Django 5.2.1 on 2025-05-22 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_core', '0002_issuedbook_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuedbook',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Issued', 'Issued'), ('Returned', 'Returned')], default='Pending', max_length=20),
        ),
    ]
